# Generated by Django 5.1.1 on 2024-10-14 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Standard',
            new_name='Class',
        ),
    ]
