# Generated by Django 5.1.1 on 2024-10-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('Ename', models.CharField(max_length=20)),
                ('Ephno', models.IntegerField()),
                ('Sal', models.FloatField()),
                ('Add', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=20)),
            ],
        ),
    ]
